### ISSUE TITLE
Optimization fails because x0 is None.

### ISSUE THREAD

**Issue by sukanya-aa** [hilo-mpc/hilo-mpc#20]
I'm trying to implement a NMPC for trajectory tracking with actual reference values(coordinates) instead of a function.

```
set_plot_backend('bokeh')

# Define the model
model = Model(name='MPC trajectory', plot_backend='bokeh', discrete=True)

#States
X = model.set_dynamical_states(['x', 'y', 'theta', 'v'])
model.set_measurements(['y_x', 'y_y', 'y_theta', 'y_v'])
model.set_measurement_equations([X[0], X[1], X[2], X[3]])

#Unwrap the states
x = X[0]
y = X[1]
theta = X[2]
v = X[3]
#Control Inputs
U = model.set_inputs(['a', 'delta'])

#Unwrap the inputs
a = U[0]
delta = U[1]

#Kinematic bicycle model
lr = 1.5
lf = 1.5
beta = ca.arctan(lr / (lr + lf) * ca.tan(delta))
w = v * ca.tan(delta) * ca.cos(beta) / (lr + lf)
dx = v * ca.cos(theta + beta)
dy = v * ca.sin(theta + beta)
dtheta = w
dv = a
model.set_dynamical_equations([dx, dy, dtheta, dv])

#Initial conditions
x0 = [-6.446169853210449, -79.05502319335938, 0, 0]
u0 = [0,0]

model.setup(options={'objective_function': 'discrete'})
nmpc = NMPC(model)

#List of some reference values
x_ref = [.....]
y_ref = [.....]

nmpc.quad_stage_cost.add_states(names=['x', 'y'], weights=[10., 10.], trajectory_tracking=True)
nmpc.quad_terminal_cost.add_states(names=['x', 'y'], weights=[10.,10.], trajectory_tracking=True)
nmpc.quad_stage_cost.add_states(names=['v'], ref=[2], weights=10)
nmpc.quad_terminal_cost.add_states(names=['v'], ref=[2], weights=10)

nmpc.horizon = 10
nmpc.set_initial_guess(x_guess=x0, u_guess=u0)
nmpc.setup(options={'objective_function': 'discrete', 'print_level': 0})

ref_sc_dict = {'x': x_ref, 'y': y_ref}
ref_tc_dict = {'x': x_ref, 'y': y_ref}

model.set_initial_conditions(x0=x0)
for step in range(l100):                                                     
     u = nmpc.optimize(xt, ref_sc=ref_sc_dict, ref_tc=ref_tc_dict)
     model.simulate(u=u)
     x0 = model.solution['xf']
```
I keep running into this error that indicates model.solution['xf'] has no values. 

```
Traceback (most recent call last):
  File ".trial.py", line 139, in <module>
    u = nmpc.optimize(x0, ref_sc=ref_sc_dict, ref_tc=ref_tc_dict)
  File "hilo_mpc\modules\controller\mpc.py", line 777, in optimize
    x0 = check_and_wrap_to_DM(x0)
  File "hilo_mpc\util\util.py", line 236, in check_and_wrap_to_DM
    raise TypeError(f"Type {type(arg)} not supported. Must be list,float,ca.DM or numpy array ")
TypeError: Type <class 'NoneType'> not supported. Must be list,float,ca.DM or numpy array
```

Is this a bug or am I making any mistakes? Please help @brunomorampc and thanks for this amazing package!

**Comment by brunomorampc** [comment]
Hey @sukanya-aa,

the problem there is that to access the next system state you need to use `model.solution['x:f']` and not `model.solution['xf']`.

Here a working code, where I put some constant reference points just for debugging

```
from hilo_mpc import  Model, NMPC
from hilo_mpc.util.plotting import set_plot_backend
import casadi as ca
set_plot_backend('bokeh')

# Define the model
model = Model(name='MPC trajectory', plot_backend='bokeh', discrete=True)

#States
X = model.set_dynamical_states(['x', 'y', 'theta', 'v'])
model.set_measurements(['y_x', 'y_y', 'y_theta', 'y_v'])
model.set_measurement_equations([X[0], X[1], X[2], X[3]])

#Unwrap the states
x = X[0]
y = X[1]
theta = X[2]
v = X[3]
#Control Inputs
U = model.set_inputs(['a', 'delta'])

#Unwrap the inputs
a = U[0]
delta = U[1]

#Kinematic bicycle model
lr = 1.5
lf = 1.5
beta = ca.arctan(lr / (lr + lf) * ca.tan(delta))
w = v * ca.tan(delta) * ca.cos(beta) / (lr + lf)
dx = v * ca.cos(theta + beta)
dy = v * ca.sin(theta + beta)
dtheta = w
dv = a
model.set_dynamical_equations([dx, dy, dtheta, dv])

#Initial conditions
x0 = [-6.446169853210449, -79.05502319335938, 0, 0]
u0 = [0,0]

model.setup(options={'objective_function': 'discrete'})
nmpc = NMPC(model)

#List of some reference values
x_ref = [1]
y_ref = [1]

nmpc.quad_stage_cost.add_states(names=['x', 'y'], weights=[10., 10.], trajectory_tracking=True)
nmpc.quad_terminal_cost.add_states(names=['x', 'y'], weights=[10.,10.], trajectory_tracking=True)
nmpc.quad_stage_cost.add_states(names=['v'], ref=[2], weights=10)
nmpc.quad_terminal_cost.add_states(names=['v'], ref=[2], weights=10)

nmpc.horizon = 10
nmpc.set_initial_guess(x_guess=x0, u_guess=u0)
nmpc.setup(options={'objective_function': 'discrete', 'print_level': 0})

ref_sc_dict = {'x': x_ref, 'y': y_ref}
ref_tc_dict = {'x': x_ref, 'y': y_ref}

model.set_initial_conditions(x0=x0)
for step in range(100):
     u = nmpc.optimize(x0, ref_sc=ref_sc_dict, ref_tc=ref_tc_dict)
     model.simulate(u=u)
     x0 = model.solution['x:f']
```

by the way are you sure the model is discrete time? If it is, keep in mind that, since you do not pass a sampling time, hilo-mpc will assume you have a sampling time of 1.

I hope this helps

**Comment by sukanya-aa** [comment]
Thank you very much. This works. But, is there a specific reason why we use `model.solution['x:f']`? Because all the examples in the hilo-mpc docs have used `xf` to get the solution.

**Comment by brunomorampc** [comment]
Hi,

you are right, the documentation needs to be updated. I'll do it this week. Thanks for pointing that out!
